### ISSUE TITLE
[BUG] Form showing up after clicking on mail approve consent link

### ISSUE THREAD

**Issue by CIMEOS** [eliashaeussler/typo3-form-consent#180]
### TYPO3 version

12.4.10

### PHP version

8.2.15

### Extension version

2.0.0

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Debian 5.10.205-2

### Current behavior

_copy of https://github.com/eliashaeussler/typo3-form-consent/issues/138 for version 2.0.0_
After clicking on the link in the consent mail the form is shown again. But the assigned images are missing.
If the page is reloaded the "alreadyApproved" notice is shown, yet the additional finishers of the "isConsentApproved()" variant are not fired.

### Expected behavior

Success notice, additional finishers of condition "isConsentApproved()" are initiated after clicking on link in consent email.

### Steps to reproduce

1. Fill out and send the form.
2. Recieve email with consent link.
3. Click on link.
4. Page shows form instead of resending the form automatically

### Additional context

```
renderingOptions:
  submitButtonLabel: Envoyer
  fieldState:
    name:
      identifier: name
      label: Nom
      type: Text
      renderingOptions:
        deleted: 0
    subject:
      identifier: subject
      label: Sujet
      type: Text
      renderingOptions:
        deleted: 0
    email:
      identifier: email
      label: Email
      type: Text
      renderingOptions:
        deleted: 0
    message:
      identifier: message
      label: Message
      type: Textarea
      renderingOptions:
        deleted: 0
    singleselect-1:
      identifier: singleselect-1
      label: 'Quelle médiathèque?'
      type: SingleSelect
      renderingOptions:
        deleted: 0
    multiselect-1:
      identifier: multiselect-1
      label: 'Liste à choix multiples'
      type: MultiSelect
      renderingOptions:
        deleted: 1
identifier: tESTFormulairedecontact-doubleoptin
label: '[TEST] Formulaire de contact - double optin'
type: Form
prototypeName: cimeosFormPrototype
variants:
  -
    identifier: post-consent-approval-variant-1
    condition: isConsentApproved()
    finishers:
      -
        identifier: FormToDatabase
      -
        identifier: EmailToSender
        options:
          subject: 'Votre demande de contact'
          recipients:
            '{email}': '{name}'
          senderAddress: no-reply@mairie-nanterre.fr
          senderName: 'Mairie de Nanterre'
          addHtmlPart: true
          attachUploads: true
          title: ''
      -
        identifier: EmailToReceiver
        options:
          subject: 'Une nouvelle demande de contact'
          recipients:
            developpement@cimeos.com: 'Developpement ciméos'
          senderAddress: no-reply@mairie-nanterre.fr
          senderName: 'Mairie de Nanterre'
          addHtmlPart: true
          attachUploads: true
          translation:
            language: 'Par défaut'
          title: ''
finishers:
  -
    options:
      message: 'Veuillez voir vos mails pour confirmer votre demande de contact.'
      contentElementUid: ''
    identifier: Confirmation
  -
    options:
      subject: 'Confirmez votre mail'
      recipientAddress: '{email}'
      recipientName: '{name}'
      senderAddress: no-reply@mairie-nanterre.fr
      senderName: 'Ville de Nanterre'
      approvalPeriod: '86400'
      showDismissLink: false
      confirmationPid: '2668'
      storagePid: '2713'
    identifier: Consent
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Étape précédente'
      nextButtonLabel: 'Étape suivante'
    identifier: page-1
    label: 'Formulaire de contact'
    type: Page
    renderables:
      -
        defaultValue: ''
        properties:
          fluidAdditionalAttributes:
            placeholder: Nom
            required: required
          elementDescription: 'Votre nom'
        identifier: name
        label: Nom
        type: Text
        validators:
          -
            identifier: NotEmpty
      -
        properties:
          options:
            'Le réseau des médiathèques de Nanterre': 'Le réseau des médiathèques de Nanterre'
            Pierre-et-Marie-Curie: Pierre-et-Marie-Curie
            'Petit Nanterre': 'Petit Nanterre'
            Flora-TristanFlora-Tristan: Flora-Tristan
            'Les Fontenelles': 'Les Fontenelles'
            "Point lecture du Chemin de l'ïle": "Point lecture du Chemin de l'ïle"
          elementDescription: 'Choisissez la médiathèque à contacter'
          prependOptionLabel: '-'
        type: SingleSelect
        identifier: singleselect-1
        label: 'Quelle médiathèque?'
      -
        defaultValue: ''
        properties:
          fluidAdditionalAttributes:
            placeholder: Sujet
            required: required
            minlength: '3'
            maxlength: '30'
          validationErrorMessages:
            -
              code: 1238110957
              message: 'La longueur de la chaine ne convient pas'
            -
              code: 1269883975
              message: 'La longueur de la chaine ne convient pas'
            -
              code: 1428504122
              message: 'La longueur de la chaine ne convient pas'
            -
              code: 1238108068
              message: 'La longueur de la chaine ne convient pas'
            -
              code: 1238108069
              message: 'La longueur de la chaine ne convient pas'
        identifier: subject
        label: Sujet
        type: Text
        validators:
          -
            identifier: NotEmpty
          -
            options:
              minimum: '3'
              maximum: '30'
            identifier: StringLength
      -
        defaultValue: ''
        properties:
          fluidAdditionalAttributes:
            placeholder: 'Votre adresse email'
            required: required
          elementDescription: 'Merci de saisir votre adresse email'
        identifier: email
        label: Email
        type: Text
        validators:
          -
            identifier: NotEmpty
          -
            identifier: EmailAddress
      -
        defaultValue: ''
        properties:
          fluidAdditionalAttributes:
            placeholder: ''
            required: required
        identifier: message
        label: Message
        type: Textarea
        validators:
          -
            identifier: NotEmpty
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
