### ISSUE TITLE
[BUG] Finisher doesn't work after approval

### ISSUE THREAD

**Issue by mlandermann** [eliashaeussler/typo3-form-consent#338]
### TYPO3 version

11.5.41

### PHP version

8.2.25

### Extension version

2.3.1

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

macOS 15.1.1

### Current behavior

After consent confirmation I get to the linked page and get approved, but the finisher mails won't send at all.
In my variants I defined my finishers like:

variants:
  -
    identifier: consent-approval
    condition: 'isConsentApproved()'
    finishers:
      -
        identifier: EmailToSender
        options:
          subject: 'Ihre Unterzeichnung: Das Manifest zur Entstigmatisierung von Suchterkrankungen'
          recipients:
            '{email-1}': ''
          senderAddress: info@XYZ.de
          senderName: 'XYZ'
          addHtmlPart: true
          attachUploads: true
          title: ''
      -
        identifier: EmailToReceiver
        options:
          subject: 'Neue Unterzeichnung: Das Manifest zur Entstigmatisierung von Suchterkrankungen'
          recipients:
            ok@XYZ.de: ''
          senderAddress: '{email-1}'
          senderName: '{singleselect-1} {text-1} {text-2}'
          replyToRecipients:
            ok@XYZ.de: ''
          addHtmlPart: true
          attachUploads: true
          translation:
            language: Standard
          title: ''

finishers:
  -
    options:
      subject: 'Bitte bestätigen Sie die Unterzeichnung des Manifests'
      recipientAddress: '{email-1}'
      recipientName: '{singleselect-1} {text-1} {text-2}'
      senderAddress: info@XYZ.de
      senderName: XYZ
      replyToAddress: info@XYZ.de
      replyToName: XYZ
      approvalPeriod: '86400'
      showDismissLink: true
      confirmationPid: '52'
      storagePid: '51'
      requireApproveVerification: false
      requireDismissVerification: false
    identifier: Consent
 
I don't know if it's a bug or sth else?
I would be grateful for ideas.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @mlandermann, how is your form rendered? Using a plugin or differently, e.g. with TypoScript? The latter won't work, see https://github.com/eliashaeussler/typo3-form-consent/issues/98#issuecomment-1505359695 for an explanation.

**Comment by mlandermann** [comment]
@eliashaeussler, my form is fully rendered using the form plugin. I simply added the EmailToReceiver and EmailToSender finishers to the variable section in the YAML file, as outlined in your documentation. Do you have any suggestions regarding this?

**Comment by eliashaeussler** [comment]
Unfortunately, I cannot reproduce this issue. Given the following form yaml:

```yaml

renderingOptions:
  submitButtonLabel: Submit
identifier: test-338
label: 'test-338'
type: Form
prototypeName: standard
variants:
  -
    identifier: consent-approval
    condition: isConsentApproved()
    finishers:
      -
        identifier: EmailToSender
        options:
          subject: 'Ihre Unterzeichnung: Das Manifest zur Entstigmatisierung von Suchterkrankungen'
          recipients:
            '{email-1}': ''
          senderAddress: info@XYZ.de
          senderName: XYZ
          addHtmlPart: true
          attachUploads: true
          title: ''
      -
        identifier: EmailToReceiver
        options:
          subject: 'Neue Unterzeichnung: Das Manifest zur Entstigmatisierung von Suchterkrankungen'
          recipients:
            ok@XYZ.de: ''
          senderAddress: '{email-1}'
          senderName: '{singleselect-1} {text-1} {text-2}'
          replyToRecipients:
            ok@XYZ.de: ''
          addHtmlPart: true
          attachUploads: true
          translation:
            language: Standard
          title: ''
finishers:
  -
    options:
      subject: 'Bitte bestätigen Sie die Unterzeichnung des Manifests'
      recipientAddress: '{email-1}'
      recipientName: '{singleselect-1} {text-1} {text-2}'
      senderAddress: info@XYZ.de
      senderName: XYZ
      replyToAddress: info@XYZ.de
      replyToName: XYZ
      approvalPeriod: '86400'
      showDismissLink: true
      confirmationPid: '2'
      storagePid: ''
      requireApproveVerification: false
      requireDismissVerification: false
    identifier: Consent
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: page-1
    label: 'Contact Form'
    type: Page
    renderables:
      -
        defaultValue: ''
        type: Email
        identifier: email-1
        label: 'Email address'
        properties:
          fluidAdditionalAttributes:
            required: required
        validators:
          -
            identifier: EmailAddress
          -
            identifier: NotEmpty
      -
        properties:
          options:
            foo: Foo
            baz: Baz
        type: SingleSelect
        identifier: singleselect-1
        label: 'Single select'
      -
        defaultValue: ''
        type: Text
        identifier: text-1
        label: Text
      -
        defaultValue: ''
        type: Text
        identifier: text-2
        label: Text
```

After approval, I receive the following e-mails:

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/03428d6f-c83e-4cfc-a211-279c510982a4" />

Can you try it with above's form yaml and check if the issue persists?
